site_name: چکیده
theme:
  name: material
  language: fa
  palette:
    - primary: teal
  font:
    text: Vazirmatn
  features:
    - navigation.footer
    - navigation.tabs
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MEgooneh/Chekideh
    - icon: fontawesome/brands/telegram
      link: https://t.me/Chekidehbook_channel
  generator: false
  
plugins:
  - search:
      lang: fa

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_css:
  - https://cdn.jsdelivr.net/gh/rastikerdar/vazirmatn@v33.003/Vazirmatn-font-face.css
  - https://cdn.jsdelivr.net/gh/rastikerdar/vazir-code-font@v1.1.2/dist/font-face.css
  - stylesheets/extra.css
copyright: این پروژه متن‌باز است.❤️

